export const Categories = [
  'Abortion',
  'Advocacy Organizations',
  'Alcohol',
  'Alternative Beliefs',
  'Dating',
  'Gambling',
  'Lingerie and Swimsuit',
  'Marijuana',
  'Nudity and Risque',
  'Other Adult Materials',
  'Pornography',
  'Sex Education',
  'Sports Hunting and War Games',
  'Tobacco',
  'Weapons (Sales)',
  'File Sharing and Storage',
  'Freeware and Software Downloads',
  'Internet Radio and TV',
  'Internet Telephony',
  'Peer-to-peer File Sharing',
  'Streaming Media and Download',
  'Armed Forces',
  'Artificial Intelligence Technology',
  'Business',
  'Charitable Organizations',
  'Cryptocurrency',
  'Finance and Banking',
  'General Organizations',
  'Government and Legal Organizations',
  'Information Technology',
  'Information and Computer Security',
  'Online Meeting',
  'Remote Access',
  'Search Engines and Portals',
  'Secure Websites',
  'URL Shortening',
  'Web Analytics',
  'Web Hosting',
  'Web-based Applications',
  'Advertising',
  'Arts and Culture',
  'Auction',
  'Brokerage and Trading',
  'Child Education',
  'Content Servers',
  'Digital Postcards',
  'Domain Parking',
  'Dynamic Content',
  'Education',
  'Entertainment',
  'Folklore',
  'Games',
  'Global Religion',
  'Health and Wellness',
  'Instant Messaging',
  'Job Search',
  'Meaningless Content',
  'Medicine',
  'News and Media',
  'Newsgroups and Message Boards',
  'Personal Privacy',
  'Personal Vehicles',
  'Personal Websites and Blogs',
  'Political Organizations',
  'Real Estate',
  'Reference',
  'Restaurant and Dining',
  'Shopping',
  'Social Networking',
  'Society and Lifestyles',
  'Sports',
  'Travel',
  'Web Chat',
  'Web-based Email',
  'Child Sexual Abuse',
  'Crypto Mining',
  'Discrimination',
  'Drug Abuse',
  'Explicit Violence',
  'Extremist Groups',
  'Hacking',
  'Illegal or Unethical',
  'Plagiarism',
  'Potentially Unwanted Program',
  'Proxy Avoidance',
  'Terrorism',
  'Dynamic DNS',
  'Malicious Websites',
  'Newly Observed Domain',
  'Newly Registered Domain',
  'Phishing',
  'Spam URLs',
  'Not Rated'
]
