name: UI CI

on:
  pull_request:
    branches:
      - production
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build
  test:
    runs-on: ubuntu-22.04
    needs: build
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npx vitest run
